config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  get 'results' => 'search#results', as: :results

  resources :podcasts, only: :show do
    resources :episodes, only: :show
  end

  resources :posts, only: [:create, :destroy] 

  post 'login' => 'registrations#login', as: :login
  post 'logout' => 'registrations#logout', as: :logout
  post 'newuser' => 'registrations#newuser', as: :newuser
  get 'useraccount' => 'registrations#useraccount', as: :useraccount
  get 'newuser' => 'registrations#newuser', as: :newuserform
  
  root 'podcasts#index'

end

app/models/api.rb
require 'json'
require 'open-uri'
require_relative './podcast.rb'
require_relative './topic.rb'
require_relative './episode.rb'
require_relative './podcasts_topic.rb'

class Api

  attr_accessor :search_hash, :url, :topic

  BASE_URL = "https://feedwrangler.net/api/v2/podcasts/search?search_term="

  def initialize(topic)
   @url = "#{BASE_URL}#{topic}"
   @topic = topic
  end

  def get_json
  	@search_hash = JSON.load(open(@url))
  end

  def load
    self.get_json
    results = []
    @search_hash["podcasts"].each do |podcast|
      p = Podcast.find_or_create_by(title: podcast["title"], identifier: podcast["podcast_id"], image_url: podcast["image_url"], feed_url: podcast["feed_url"])
      episode_hash = JSON.load(open("https://feedwrangler.net/api/v2/podcasts/show?podcast_id=#{p.identifier}"))
      p.summary = episode_hash["podcast"]["summary"]
      p.save
      results << p
      episode_hash["podcast"]["recent_episodes"].each do |episode|
        e = Episode.find_or_create_by(title: episode["title"], url: episode["audio_url"], podcast_id: p.id)
      end
      t = Topic.find_by(:name => @topic.capitalize)
      if t
        PodcastsTopic.create(:podcast_id => p.id, :topic_id => t.id)
      else 
        t = Topic.create(:name => @topic.capitalize)  
        PodcastsTopic.create(:podcast_id => p.id, :topic_id => t.id)
      end
    end
    results
  end
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
  has_many :posts
end

app/models/episodes.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
  has_many :posts
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :episodes
	has_many :user_podcasts
	has_many :users, through: :user_podcasts
	has_many :posts
	has_many :topics, through: :podcasts_topics
	has_many :podcasts_topics
end

app/models/podcasts.rb
class Podcast < ActiveRecord::Base
  has_many :episodes
	has_many :user_podcasts
	has_many :users, through: :user_podcasts
	has_many :posts
	has_many :topics, through: :podcasts_topics
	has_many :podcasts_topics
end

app/models/podcasts_topic.rb
class PodcastsTopic < ActiveRecord::Base

	belongs_to :podcast
	belongs_to :topic

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :podcast
  belongs_to :episode

  def username=(name)
    self.user = User.find_or_create_by(:name => name)
  end

  def username
    self.user.present? ? self.user.name : ""
  end

end

app/models/posts.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :podcast
  belongs_to :episode

  def username=(name)
    self.user = User.find_or_create_by(:name => name)
  end

  def username
    self.user.present? ? self.user.name : ""
  end

end

app/models/search.rb
class Search
	attr_accessor :keyword, :topic, :podcasts

	def initialize(keyword)
		@keyword = keyword
	end

	def podcasts
		if topic.podcasts.any?
			topic.podcasts
		else
			Api.new(keyword).load
		end
	end

	private

	def topic
		@topic = Topic.find_or_create_by(name: keyword)
	end
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  has_many :subtopics
  has_many :podcasts, through: :podcasts_topics
  has_many :podcasts_topics
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_podcasts
  has_many :podcasts, through: :user_podcasts
  has_many :posts

  def name
    @name = "#{first_name} #{last_name}"
  end
  
end

app/models/user_podcast.rb
class UserPodcast < ActiveRecord::Base
	belongs_to :user
	belongs_to :podcast
end

app/models/user_podcasts.rb
class UserPodcast < ActiveRecord::Base
	belongs_to :user
	belongs_to :podcast
end

app/models/users.rb
class User < ActiveRecord::Base

  has_many :user_podcasts
  has_many :podcasts, through: :user_podcasts
  has_many :posts

  def name
    @name = "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def show
    @episode = Episode.find(params[:id])
    @post = Post.new
  end

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  def index
    @newuser = true if flash[:newuser]
    @topics = Topic.all
    @categories_array = ["Arts", "Business", "Comedy", "Education", "Hobbies", "Government", "Health", "Kids", "Music", "News", "Politics", "Religion", "Science", "Medicine", "Culture", "Sports", "TV", "Film", "Technology"]

    # # devise login
    # self.resource = resource_class.new(sign_in_params)
    # clean_up_passwords(resource)
    # yield resource if block_given?
    # respond_with(resource, serialize_options(resource))
  end
  
  def show
    @podcast = Podcast.find(params[:id])
    @post = Post.new
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def locate_redirect(post)
    if post.podcast_id
      redirect_to podcast_path(post.podcast)
    elsif post.episode_id
      redirect_to podcast_episode_path(post.episode.podcast, post.episode)
      # episode_id = post.episode_id
      # episode = Episode.find(episode_id)
      # podcast = episode.podcast
      # redirect "/podcasts/#{podcast.id}/#{episode_id}" 
    end
  end

  def create 
    @post = Post.create(post_params)
    if @post.podcast_id
      @podcast = Podcast.find(params[:post][:podcast_id])
    elsif @post.episode_id
      @episode = Episode.find(params[:post][:episode_id])
    end
    locate_redirect(@post)
  end  

  def destroy
   @post = Post.find(params[:id])
   @post.destroy
    locate_redirect(@post)
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :content, :podcast_id, :episode_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def login
    begin
      @user = User.find_by(:username => params[:username])
      session[:user_id] = @user.id
    rescue
      flash[:invaliduser] = "Invalid username. Please try again or create a new account."
    end
    redirect_to root_path
  end

  def logout
    session[:user_id] = ""
    redirect_to root_path
  end

	def newuser
		@user = User.create(params[:user])
    session[:user_id] = @user.id
    flash[:newuser] = "Thank you for registering for this site! We're thrilled to have you!"
    redirect_to root_path
	end

  def useraccount
    @user = current_user
  end

	def newuserform
		@user = User.new
	end	

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def results
		@keyword = params[:searchkeyword]
		if @keyword
			@podcasts = Search.new(@keyword).podcasts
	  else
	  	redirect_to root_path, notice: "pick a keyword"
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/episodes/show.html.erb
<a href="/">Home</a>
<p><a href="/podcasts/<%= @episode.podcast_id %>">Back to <%= @episode.podcast.title %></a></p>

<h1><a href="<%= @episode.url %>"><%= @episode.title %></a></h1>
<img width='150' src="<%= @episode.podcast.image_url %>">


<p>Add Your Voice:</p>

<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content, "Comment" %>
	<%= f.text_area :content %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :episode_id, :value => @episode.id %>
	<%= f.submit %>
<% end %>

<p>Comments:</p>

<% @episode.posts.each do |post| %>
	<%= render 'posts/comment', :post => post %>
<% end %>

app/views/podcasts/_login.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/podcasts/episodes.html.erb
<a href="/">Home</a>
<p><a href="/podcasts/<%= @episode.podcast_id %>">Back to <%= @episode.podcast.title %></a></p>

<h1><a href="<%= @episode.url %>"><%= @episode.title %></a></h1>
<img width='150' src="<%= @podcast.image_url %>">


<p>Add Your Voice:</p>

<form action='/posts' method='post'>
	<p><label for='title'>Title</label>
	<input name="post[title]" type='text' id='title'/></p>
	<p><label for='comment'>Comment</label>
	<textarea name="post[content]" id='comment'></textarea></p>
	<input type='hidden' name='post[user_id]' value="<%= current_user.id %>"/>
	<input type='hidden' name='post[episode_id]' value="<%= @episode.id %>"/>
	<input type="submit"/>
</form>

<p>Comments:</p>

<% @episode.posts.each do |post| %>
	<p>Date: <%= post.created_at %></p>
	<p>Title: <%= post.title %></p>
  <p>Content: <%= post.content %></p>
  <p>Author: <%= post.user.name %></p>
  <a href="/posts/<%= post.id %>/edit">Edit</a>

	<form action='/posts/<%= post.id %>/delete' method='post'>
		<input class=delete-button type="submit" value="Delete"/>
	</form>

<% end %>

app/views/podcasts/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Podfetti</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <div class="form-group">
          <form action='/results' method="get" class="navbar-form navbar-left" role="search">
            <input type="text" name="searchkeyword" class="custom-form form-control" placeholder="Search Podcasts by Keyword"/>       
            <input type="submit" class="btn btn-default"></input>
          </form>      
      </ul>
    <div>

      <% if !user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
           <%#= render 'login' %> <!-- tried to pull in the devise login partial here. didn't work because there are many methods passed into the devise new route. to be attempted another time. -->
           <%= link_to "Sign In", new_user_session_path %>
        </ul>

      <% else %>

        <ul class="nav navbar-nav navbar-right">
          <!-- <p><%#= flash[:newuser] if current_user %></p>  this has to be added to the devise create route -->
          <p class='test'>Hello, <%= current_user.email %>!
          <p><%= link_to "Your Account", useraccount_path %> | <%= link_to "Log Out", destroy_user_session_path, :method => :delete %></p>
        </ul>

      <% end %>

    </div>
  </div>
</div>
  </nav>

<blockquote class="pull-right">
  <p>Let’s start with a simple fact:<br>
  More people have downloaded Serial <br> 
  than have watched Girls, Mad Men, or Louie.</p>
  <small><cite title="Source Title"><a href="http://www.fastcompany.com/3041522/pod-power" target="_blank">Fast Company</a></cite></small>
</blockquote>

<div class="jumbotron">
    <h5>Or, find podcasts by common categories:</h5>
    <ul>
    <% @categories_array.each do |category| %>
      <li><%= link_to category, results_path(:searchkeyword => category) %></li>
    <% end %>
    </ul>
</div>

app/views/podcasts/podcasts.html.erb
<a href="/">Home</a>

<h1><a href="<%= @podcast.feed_url %>"><%= @podcast.title %></a></h1>
<img width='150' src="<%= @podcast.image_url %>">
<p><% @podcast.summary %></p>

<% @podcast.episodes.each do |episode| %>
	<li><a href="/podcasts/<%= episode.podcast_id %>/<%= episode.id %>"><%= episode.title %></a></li>
<% end %>

<p>Add Your Voice:</p>

<form action='/posts' method='post'>
	<p><label for='title'>Title</label>
	<input name="post[title]" type='text' id='title'/></p>
	<p><label for='comment'>Comment</label>
	<textarea name="post[content]" id='comment'></textarea></p>
	<input type='hidden' name='post[user_id]' value="<%= current_user.id %>"/>
	<input type='hidden' name='post[podcast_id]' value="<%= @podcast.id %>"/>
	<input type="submit"/>
</form>

<p>Comments:</p>

<% @podcast.posts.each do |post| %>
	<p>Date: <%= post.created_at %></p>
	<p>Title: <%= post.title %></p>
  <p>Content: <%= post.content %></p>
  <p>Author: <%= post.user.name %></p>
  <a href="/posts/<%= post.id %>/edit">Edit</a>
  
	<form action='/posts/<%= post.id %>/delete' method='post'>
		<input class=delete-button type="submit" value="Delete"/>
	</form>

<% end %>

app/views/podcasts/results.html.erb
<a href="/">Home</a>

<p>You searched for: <%= @keyword %></p>

<% @podcasts.each do |podcast| %>
	<ul>
		<li><a href="/podcasts/<%= podcast.id %>"><%= podcast.title %></a></li>
		<img width='150' src="<%= podcast.image_url %>">
	</ul>
<% end %>

app/views/podcasts/show.html.erb
<a href="/">Home</a>

<h1><a href="<%= @podcast.feed_url %>"><%= @podcast.title %></a></h1>
<img width='150' src="<%= @podcast.image_url %>">
<p><% @podcast.summary %></p>

<% @podcast.episodes.each do |episode| %>
	<li><%= link_to episode.title, [@podcast, episode] %></li>
<% end %>

<p>Add Your Voice:</p>

<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content, "Comment" %>
	<%= f.text_area :content %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :podcast_id, :value => @podcast.id %>
	<%= f.submit %>
<% end %>

<p>Comments:</p>

<% @podcast.posts.each do |post| %>
	<%= render 'posts/comment', :post => post %>
<% end %>

app/views/posts/_comment.html.erb
<p>Date: <%= post.created_at.strftime "%m/%d/%y at %l:%M %p" %></p>
<p>Title: <%= post.title %></p>
<p>Content: <%= post.content %></p>
<p>Author: <%= post.user.email %></p>
<!-- <a href="/posts/<%= post.id %>/edit">Edit</a> -->

<%= link_to "Delete", post_path(post), :method => :delete, :class => "btn btn-default" %>

app/views/search/results.html.erb
<a href="/">Home</a>

<p>You searched for: <%= @keyword %></p>

<% @podcasts.each do |podcast| %>
	<ul>
		<li><a href="/podcasts/<%= podcast.id %>"><%= podcast.title %></a></li>
		<img width='150' src="<%= podcast.image_url %>">
	</ul>
<% end %>